package com.petcare.domain.notification;

public enum NotificationType {
	RESERVATION_REQUESTED,
	RESERVATION_CONFIRMED,
	RESERVATION_REJECTED,
	RESERVATION_CANCELLED,
	RESERVATION_REMINDER,
	VACCINATION_DUE_SOON,
	FAVORITE_HOSPITAL_NEW_SLOT,
	CHAT_MESSAGE_RECEIVED
}
