spring:
  application:
    name: petcare

  datasource:
    url: jdbc:mysql://localhost:3306/petcare
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour (ms)
  refresh-expiration: 1209600000 # 14 days (ms)

app:
  upload:
    pet-image-dir: uploads/pets
    hospital-image-dir: uploads/hospitals
  admin:
    bootstrap-email: ${ADMIN_EMAIL:}
    bootstrap-password: ${ADMIN_PASSWORD:}
